// Code generated by go-asmgen. DO NOT EDIT.

//go:build riscv64

#include "textflag.h"

TEXT ·decodeGroupsRVV(SB), NOSPLIT, $0-56
	MOV dst+0(FP), X5
	MOV ctrl+8(FP), X6
	MOV data+16(FP), X7
	MOV groups+24(FP), X8
	MOV shuf+32(FP), X9
	MOV lens+40(FP), X10
	VSETVLI $16, E8, M1, TA, MA, X11
	MOV $0, X12
	MOV $0, X13
loop:
	BGE X12, X8, done
	ADD X6, X12, X14
	MOVBU (X14), X15
	SLLI $4, X15, X16
	ADD X9, X16, X16
	VLE8V (X16), V2
	ADD X7, X13, X17
	VLE8V (X17), V1
	VRGATHERVV V2, V1, V3
	SLLI $4, X12, X18
	ADD X5, X18, X18
	VSE8V V3, (X18)
	ADD X10, X15, X19
	MOVBU (X19), X20
	ADD X13, X20, X13
	ADD $1, X12, X12
	JMP loop
done:
	MOV X13, ret+48(FP)
	RET

