//go:build amd64

package streamvbyte

import "golang.org/x/sys/cpu"

// decodeGroupsSSE decodes `groups` complete groups of four uint32 using SSSE3
// PSHUFB: each iteration loads one control byte, loads 16 data bytes, applies the
// shuffleTable[ctrl] mask (PSHUFB writes zero for any mask byte with bit 7 set,
// which zero-extends each lane), stores 16 result bytes, and advances the data
// pointer by lengthTable[ctrl]. Returns the data bytes consumed. The caller
// guarantees 16 readable data bytes at every requested group. Generated by
// go-asmgen (decode_amd64_gen.go), in decode_amd64.s.
func decodeGroupsSSE(dst *uint32, ctrl *uint8, data *uint8, groups int, shuf *uint8, lens *uint8) int

// hasSSSE3 gates the PSHUFB kernel; PSHUFB is SSSE3, not in the SSE2 baseline.
var hasSSSE3 = cpu.X86.HasSSSE3

func decode(dst []uint32, src []byte, n int) int {
	cl := controlLen(n)
	groups := n / 4
	safe := 0
	var consumed int
	if hasSSSE3 {
		safe = safeGroups(src, cl, groups)
		if safe > 0 {
			consumed = decodeGroupsSSE(&dst[0], &src[0], &src[cl], safe,
				&shuffleTable[0][0], &lengthTable[0])
		}
	}
	return decodeTail(dst, src, n, safe, consumed)
}
