//go:build ppc64le

package streamvbyte

// decodeGroupsVSX decodes `groups` complete groups of four uint32 using VMX
// VPERM. Each iteration loads one control byte, loads 16 data bytes, loads the
// permTable[ctrl] mask, permutes (result byte i = concat(data, zero)[mask[i]];
// mask bytes that must be zero point at the all-zero companion register, index
// 16), stores 16 result bytes, and advances the data pointer by
// lengthTable[ctrl]. Returns the data bytes consumed. The caller guarantees 16
// readable data bytes at every requested group. Generated by go-asmgen
// (decode_ppc64le_gen.go), in decode_ppc64le.s. permTable (not shuffleTable) is
// used because VPERM has no high-bit-zeroes rule. The kernel is built entirely
// from ISA-2.07 (POWER8-baseline) ops — the element-order vector load/store is
// emitted as LXVD2X/STXVD2X + a VPERM byte-reversal instead of the ISA-3.0
// LXVB16X/STXVB16X — so it runs natively on POWER8 too (gated by hasVSXDecode,
// which is true on POWER8+, since the decode kernel beats the scalar codec there).
func decodeGroupsVSX(dst *uint32, ctrl *uint8, data *uint8, groups int, perm *uint8, lens *uint8) int

func decode(dst []uint32, src []byte, n int) int {
	cl := controlLen(n)
	groups := n / 4
	safe := 0
	if hasVSXDecode {
		safe = safeGroups(src, cl, groups)
	}
	var consumed int
	if safe > 0 {
		consumed = decodeGroupsVSX(&dst[0], &src[0], &src[cl], safe,
			&permTable[0][0], &lengthTable[0])
	}
	return decodeTail(dst, src, n, safe, consumed)
}
