//go:build loong64

package streamvbyte

// decodeGroupsLSX decodes `groups` complete groups of four uint32 using the LSX
// byte shuffle vshuf.b: each iteration loads one control byte, loads 16 data
// bytes, loads the permTable[ctrl] mask, shuffles (result[i] = data[mask[i]] for
// mask[i] in 0..15, or 0 when mask[i] == 16 which selects an all-zero companion
// register, zero-extending each lane), stores 16 result bytes, and advances the
// data pointer by lengthTable[ctrl]. Returns the data bytes consumed. The caller
// guarantees 16 readable data bytes at every requested group. Generated by
// go-asmgen (decode_loong64_gen.go), in decode_loong64.s. vshuf.b indexes a
// 32-byte register pair and does NOT zero on a high index bit, so it uses
// permTable (zero -> index 16) and a zero register, like the VPERM targets.
func decodeGroupsLSX(dst *uint32, ctrl *uint8, data *uint8, groups int, perm *uint8, lens *uint8) int

func decode(dst []uint32, src []byte, n int) int {
	cl := controlLen(n)
	groups := n / 4
	safe := safeGroups(src, cl, groups)
	var consumed int
	if safe > 0 {
		consumed = decodeGroupsLSX(&dst[0], &src[0], &src[cl], safe,
			&permTable[0][0], &lengthTable[0])
	}
	return decodeTail(dst, src, n, safe, consumed)
}
