//go:build ppc64le

package streamvbyte

// decodeGroupsVSX decodes `groups` complete groups of four uint32 using VMX
// VPERM. Each iteration loads one control byte, loads 16 data bytes, loads the
// permTable[ctrl] mask, permutes (result byte i = concat(data, zero)[mask[i]];
// mask bytes that must be zero point at the all-zero companion register, index
// 16), stores 16 result bytes, and advances the data pointer by
// lengthTable[ctrl]. Returns the data bytes consumed. The caller guarantees 16
// readable data bytes at every requested group. Generated by go-asmgen
// (decode_ppc64le_gen.go), in decode_ppc64le.s. permTable (not shuffleTable) is
// used because VPERM has no high-bit-zeroes rule. The kernel uses ISA-3.0
// (POWER9) instructions (LXVB16X/STXVB16X), which raise SIGILL on POWER8, so it
// runs only when hasVSX (shared with the encode kernel) reports POWER9+.
func decodeGroupsVSX(dst *uint32, ctrl *uint8, data *uint8, groups int, perm *uint8, lens *uint8) int

func decode(dst []uint32, src []byte, n int) int {
	cl := controlLen(n)
	groups := n / 4
	safe := 0
	if hasVSX {
		safe = safeGroups(src, cl, groups)
	}
	var consumed int
	if safe > 0 {
		consumed = decodeGroupsVSX(&dst[0], &src[0], &src[cl], safe,
			&permTable[0][0], &lengthTable[0])
	}
	return decodeTail(dst, src, n, safe, consumed)
}
