// Code generated by go-asmgen. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

TEXT ·decodeGroupsSSE(SB), NOSPLIT, $0-56
	MOVQ dst+0(FP), DI
	MOVQ ctrl+8(FP), SI
	MOVQ data+16(FP), DX
	MOVQ groups+24(FP), CX
	MOVQ shuf+32(FP), R8
	MOVQ lens+40(FP), R9
	XORQ R10, R10
	XORQ R11, R11
loop:
	CMPQ R10, CX
	JGE done
	MOVBLZX (SI)(R10*1), R12
	MOVQ R12, R13
	SHLQ $4, R13
	ADDQ R8, R13
	MOVOU (R13), X1
	MOVOU (DX)(R11*1), X0
	PSHUFB X1, X0
	MOVQ R10, R14
	SHLQ $4, R14
	MOVOU X0, (DI)(R14*1)
	MOVBLZX (R9)(R12*1), R15
	ADDQ R15, R11
	INCQ R10
	JMP loop
done:
	MOVQ R11, ret+48(FP)
	RET

