//go:build s390x

package streamvbyte

// decodeGroupsVX decodes `groups` complete groups of four uint32 using the
// vector-facility VPERM on z13+ (baseline, no runtime dispatch). Each iteration
// loads one control byte, loads 16 data bytes, loads the permTableBE[ctrl] mask,
// permutes the bytes into four big-endian uint32 lanes (with zero bytes pulled
// from an all-zero companion register), stores 16 result bytes, and advances the
// data pointer by lengthTable[ctrl]. Returns the data bytes consumed. The caller
// guarantees 16 readable data bytes at every requested group. Generated by
// go-asmgen (decode_s390x_gen.go), in decode_s390x.s.
//
// s390x is big-endian: permTableBE reverses each lane's bytes (the data stream is
// LSB-first but a stored uint32 is MSB-first), so the decoded values are correct
// native big-endian uint32s. See decode_s390x_gen.go and tables.go.
func decodeGroupsVX(dst *uint32, ctrl *uint8, data *uint8, groups int, perm *uint8, lens *uint8) int

func decode(dst []uint32, src []byte, n int) int {
	cl := controlLen(n)
	groups := n / 4
	safe := safeGroups(src, cl, groups)
	var consumed int
	if safe > 0 {
		consumed = decodeGroupsVX(&dst[0], &src[0], &src[cl], safe,
			&permTableBE[0][0], &lengthTable[0])
	}
	return decodeTail(dst, src, n, safe, consumed)
}
