//go:build arm64

package streamvbyte

// decodeGroupsNEON decodes `groups` complete groups of four uint32 using NEON
// VTBL: each iteration loads one control byte, loads 16 data bytes, applies the
// shuffleTable[ctrl] mask (VTBL, with out-of-range indices producing zero
// bytes), stores 16 result bytes, and advances the data pointer by
// lengthTable[ctrl]. It returns the number of data bytes consumed.
//
// The caller guarantees that at least 16 data bytes are readable at every group
// it asks for, so the wide load never runs off the end of src. Generated by
// go-asmgen (decode_arm64_gen.go), in decode_arm64.s.
func decodeGroupsNEON(dst *uint32, ctrl *uint8, data *uint8, groups int, shuf *uint8, lens *uint8) int

func decode(dst []uint32, src []byte, n int) int {
	cl := controlLen(n)
	groups := n / 4
	safe := safeGroups(src, cl, groups)
	var consumed int
	if safe > 0 {
		consumed = decodeGroupsNEON(&dst[0], &src[0], &src[cl], safe,
			&shuffleTable[0][0], &lengthTable[0])
	}
	return decodeTail(dst, src, n, safe, consumed)
}
