//go:build riscv64

package streamvbyte

// decodeGroupsRVV decodes `groups` complete groups of four uint32 using the RVV
// byte gather vrgather.vv: each iteration loads one control byte, loads 16 data
// bytes, loads the shuffleTable[ctrl] mask, gathers (result[i] = data[mask[i]],
// or 0 when mask[i] >= VL=16, which zero-extends each lane), stores 16 result
// bytes, and advances the data pointer by lengthTable[ctrl]. Returns the data
// bytes consumed. The caller guarantees 16 readable data bytes at every
// requested group. Generated by go-asmgen (decode_riscv64_gen.go), in
// decode_riscv64.s.
func decodeGroupsRVV(dst *uint32, ctrl *uint8, data *uint8, groups int, shuf *uint8, lens *uint8) int

func decode(dst []uint32, src []byte, n int) int {
	cl := controlLen(n)
	groups := n / 4
	safe := safeGroups(src, cl, groups)
	var consumed int
	if safe > 0 {
		consumed = decodeGroupsRVV(&dst[0], &src[0], &src[cl], safe,
			&shuffleTable[0][0], &lengthTable[0])
	}
	return decodeTail(dst, src, n, safe, consumed)
}
