// Code generated by go-asmgen. DO NOT EDIT.

//go:build loong64

#include "textflag.h"

TEXT ·decodeGroupsLSX(SB), NOSPLIT, $0-56
	MOVV dst+0(FP), R4
	MOVV ctrl+8(FP), R5
	MOVV data+16(FP), R6
	MOVV groups+24(FP), R7
	MOVV perm+32(FP), R8
	MOVV lens+40(FP), R9
	MOVV $0, R10
	MOVV $0, R11
	VXORV V3, V3, V3
loop:
	BGE R10, R7, done
	ADDVU R5, R10, R12
	MOVBU (R12), R13
	SLLV $4, R13, R14
	ADDVU R8, R14, R14
	VMOVQ (R14), V1
	ADDVU R6, R11, R15
	VMOVQ (R15), V0
	VSHUFB V1, V0, V3, V2
	SLLV $4, R10, R16
	ADDVU R4, R16, R16
	VMOVQ V2, (R16)
	ADDVU R9, R13, R17
	MOVBU (R17), R18
	ADDVU R11, R18, R11
	ADDVU $1, R10, R10
	JMP loop
done:
	MOVV R11, ret+48(FP)
	RET

