//go:build arm64

package streamvbyte

// encodeGroupsNEON compacts `groups` complete groups of four uint32 into the data
// stream using NEON VTBL: each iteration loads one (precomputed) control byte,
// loads the 16 source bytes of the group (four uint32), applies the
// encodeShuffleTable[ctrl] compaction mask (VTBL, with out-of-range indices
// producing zero bytes), stores 16 bytes at the running data cursor, and advances
// the data pointer by lengthTable[ctrl]. Only lengthTable[ctrl] bytes are
// significant; the trailing zeros are overwritten by the next group (or left in
// the EncodedMaxLen slack). Returns the data bytes written.
//
// The caller guarantees that at least 16 data bytes are writable at every group
// it asks for, so the wide store never runs off the end of dst. Generated by
// go-asmgen (encode_arm64_gen.go), in encode_arm64.s.
func encodeGroupsNEON(data *uint8, ctrl *uint8, src *uint32, groups int, shuf *uint8, lens *uint8) int

func encode(dst []byte, src []uint32, n int) int {
	cl := controlLen(n)
	groups := n / 4
	ctrl := dst[:cl]
	data := dst[cl:]
	safe := encodeSafeGroups(ctrl, src, groups, len(data))
	consumed := 0
	if safe > 0 {
		consumed = encodeGroupsNEON(&data[0], &ctrl[0], &src[0], safe,
			&encodeShuffleTable[0][0], &lengthTable[0])
	}
	dp := encodeTail(dst, src, n, safe, consumed)
	return cl + dp
}
