// Code generated by go-asmgen. DO NOT EDIT.

//go:build arm64

#include "textflag.h"

TEXT ·encodeGroupsNEON(SB), NOSPLIT, $0-56
	MOVD data+0(FP), R0
	MOVD ctrl+8(FP), R1
	MOVD src+16(FP), R2
	MOVD groups+24(FP), R3
	MOVD shuf+32(FP), R4
	MOVD lens+40(FP), R5
	MOVD $0, R6
	MOVD $0, R7
loop:
	CMP R3, R6
	BGE done
	MOVBU (R1)(R6), R8
	LSL $4, R8, R9
	ADD R4, R9, R9
	VLD1 (R9), [V1.B16]
	LSL $4, R6, R10
	ADD R2, R10, R10
	VLD1 (R10), [V0.B16]
	VTBL V1.B16, [V0.B16], V2.B16
	ADD R0, R7, R11
	VST1 [V2.B16], (R11)
	MOVBU (R5)(R8), R12
	ADD R12, R7, R7
	ADD $1, R6, R6
	JMP loop
done:
	MOVD R7, ret+48(FP)
	RET

