//go:build ppc64le

package streamvbyte

// encodeGroupsVSX compacts `groups` complete groups of four uint32 into the data
// stream using VMX VPERM on POWER8+ (VSX/VMX baseline, no runtime dispatch). Each
// iteration loads one (precomputed) control byte, loads the 16 source bytes of
// the group, loads the encodeShuffleTablePerm[ctrl] mask, permutes (result byte i
// = concat(src, zero)[mask[i]]; mask bytes that must be zero point at the all-zero
// companion register, index 16), stores 16 bytes at the running data cursor, and
// advances the data pointer by lengthTable[ctrl]. Only lengthTable[ctrl] bytes
// are significant; the trailing zeros are overwritten by the next group (or left
// in the EncodedMaxLen slack). Returns the data bytes written. The caller
// guarantees 16 writable data bytes at every requested group. Generated by
// go-asmgen (encode_ppc64le_gen.go), in encode_ppc64le.s. encodeShuffleTablePerm
// (not encodeShuffleTable) is used because VPERM has no high-bit-zeroes rule.
func encodeGroupsVSX(data *uint8, ctrl *uint8, src *uint32, groups int, perm *uint8, lens *uint8) int

func encode(dst []byte, src []uint32, n int) int {
	cl := controlLen(n)
	groups := n / 4
	ctrl := dst[:cl]
	data := dst[cl:]
	safe := encodeSafeGroups(ctrl, src, groups, len(data))
	consumed := 0
	if safe > 0 {
		consumed = encodeGroupsVSX(&data[0], &ctrl[0], &src[0], safe,
			&encodeShuffleTablePerm[0][0], &lengthTable[0])
	}
	dp := encodeTail(dst, src, n, safe, consumed)
	return cl + dp
}
