//go:build ppc64le

package streamvbyte

import "golang.org/x/sys/cpu"

// encodeGroupsVSX compacts `groups` complete groups of four uint32 into the data
// stream using VMX VPERM. Each iteration loads one (precomputed) control byte,
// loads the 16 source bytes of the group, loads the encodeShuffleTablePerm[ctrl]
// mask, permutes (result byte i = concat(src, zero)[mask[i]]; mask bytes that
// must be zero point at the all-zero companion register, index 16), stores 16
// bytes at the running data cursor, and advances the data pointer by
// lengthTable[ctrl]. Only lengthTable[ctrl] bytes are significant; the trailing
// zeros are overwritten by the next group (or left in the EncodedMaxLen slack).
// Returns the data bytes written. The caller guarantees 16 writable data bytes
// at every requested group. Generated by go-asmgen (encode_ppc64le_gen.go), in
// encode_ppc64le.s. encodeShuffleTablePerm (not encodeShuffleTable) is used
// because VPERM has no high-bit-zeroes rule. The kernel uses ISA-3.0 (POWER9)
// instructions (LXVB16X/STXVB16X), which raise SIGILL on POWER8, so it runs only
// when hasVSX reports POWER9+.
func encodeGroupsVSX(data *uint8, ctrl *uint8, src *uint32, groups int, perm *uint8, lens *uint8) int

// hasVSX is the shared dispatch flag for both the encode and decode VSX kernels.
// They emit ISA-3.0 (POWER9) instructions (LXVB16X/STXVB16X) that are illegal on
// POWER8, so they are gated on POWER9 detection; on POWER8 the kernels are never
// called and encodeTail/decodeTail (the complete scalar reference codec) does all
// the work. It is a var (not a const) so the dispatch test can also drive the
// no-SIMD fallback on a POWER9+ host.
var hasVSX = cpu.PPC64.IsPOWER9

func encode(dst []byte, src []uint32, n int) int {
	cl := controlLen(n)
	groups := n / 4
	ctrl := dst[:cl]
	data := dst[cl:]
	safe := 0
	if hasVSX {
		safe = encodeSafeGroups(ctrl, src, groups, len(data))
	}
	consumed := 0
	if safe > 0 {
		consumed = encodeGroupsVSX(&data[0], &ctrl[0], &src[0], safe,
			&encodeShuffleTablePerm[0][0], &lengthTable[0])
	}
	dp := encodeTail(dst, src, n, safe, consumed)
	return cl + dp
}
