// Code generated by go-asmgen. DO NOT EDIT.

//go:build ppc64le

#include "textflag.h"

TEXT ·encodeGroupsVSX(SB), NOSPLIT, $0-56
	MOVD data+0(FP), R3
	MOVD ctrl+8(FP), R4
	MOVD src+16(FP), R5
	MOVD groups+24(FP), R6
	MOVD perm+32(FP), R7
	MOVD lens+40(FP), R8
	MOVD $0, R9
	MOVD $0, R10
	VSPLTISB $0, V2
loop:
	CMP R9, R6
	BGE done
	ADD R4, R9, R11
	MOVBZ (R11), R12
	SLD $4, R12, R14
	ADD R7, R14, R14
	LXVB16X (R14), VS33
	SLD $4, R9, R15
	ADD R5, R15, R15
	LXVB16X (R15), VS32
	VPERM V0, V2, V1, V3
	ADD R3, R10, R16
	STXVB16X VS35, (R16)
	ADD R8, R12, R17
	MOVBZ (R17), R18
	ADD R10, R18, R10
	ADD $1, R9, R9
	BR loop
done:
	MOVD R10, ret+48(FP)
	RET

