//go:build riscv64

package streamvbyte

// encodeGroupsRVV compacts `groups` complete groups of four uint32 into the data
// stream using the RVV byte gather vrgather.vv: each iteration loads one
// (precomputed) control byte, loads the 16 source bytes of the group, loads the
// encodeShuffleTable[ctrl] mask, gathers (result[i] = src[mask[i]], or 0 when
// mask[i] >= VL=16, which clears the unused trailing bytes), stores 16 bytes at
// the running data cursor, and advances the data pointer by lengthTable[ctrl].
// Only lengthTable[ctrl] bytes are significant; the trailing zeros are
// overwritten by the next group (or left in the EncodedMaxLen slack). Returns the
// data bytes written. The caller guarantees 16 writable data bytes at every
// requested group. Generated by go-asmgen (encode_riscv64_gen.go), in
// encode_riscv64.s.
func encodeGroupsRVV(data *uint8, ctrl *uint8, src *uint32, groups int, shuf *uint8, lens *uint8) int

func encode(dst []byte, src []uint32, n int) int {
	cl := controlLen(n)
	groups := n / 4
	ctrl := dst[:cl]
	data := dst[cl:]
	safe := encodeSafeGroups(ctrl, src, groups, len(data))
	consumed := 0
	if safe > 0 {
		consumed = encodeGroupsRVV(&data[0], &ctrl[0], &src[0], safe,
			&encodeShuffleTable[0][0], &lengthTable[0])
	}
	dp := encodeTail(dst, src, n, safe, consumed)
	return cl + dp
}
