//go:build ppc64le

package streamvbyte

import "golang.org/x/sys/cpu"

// encodeGroupsVSX compacts `groups` complete groups of four uint32 into the data
// stream using VMX VPERM. Each iteration loads one (precomputed) control byte,
// loads the 16 source bytes of the group, loads the encodeShuffleTablePerm[ctrl]
// mask, permutes (result byte i = concat(src, zero)[mask[i]]; mask bytes that
// must be zero point at the all-zero companion register, index 16), stores 16
// bytes at the running data cursor, and advances the data pointer by
// lengthTable[ctrl]. Only lengthTable[ctrl] bytes are significant; the trailing
// zeros are overwritten by the next group (or left in the EncodedMaxLen slack).
// Returns the data bytes written. The caller guarantees 16 writable data bytes
// at every requested group. Generated by go-asmgen (encode_ppc64le_gen.go), in
// encode_ppc64le.s. encodeShuffleTablePerm (not encodeShuffleTable) is used
// because VPERM has no high-bit-zeroes rule. The kernel is built entirely from
// ISA-2.07 (POWER8-baseline) ops — the element-order vector load/store is emitted
// as LXVD2X/STXVD2X + a VPERM byte-reversal instead of the ISA-3.0
// LXVB16X/STXVB16X — so it runs natively on POWER8 too.
func encodeGroupsVSX(data *uint8, ctrl *uint8, src *uint32, groups int, perm *uint8, lens *uint8) int

// Both VSX kernels are now ISA-2.07 (VSX/AltiVec is the ppc64le baseline, POWER8),
// so neither SIGILLs on POWER8 anymore. They are gated separately, however,
// because their POWER8 economics differ (both measured on cfarm112, POWER8E):
//
//   - hasVSXDecode (POWER8+): the decode kernel BEATS the scalar codec by ~4.3×
//     on POWER8E (and stays a win on POWER9), so it runs everywhere.
//   - hasVSXEncode (POWER9 only): the encode kernel only ties / marginally trails
//     the scalar codec on POWER8E (size-dependent, ~tie at best, a loss at the
//     common 1 KiB and 64 KiB sizes), so per the "don't ship a kernel slower than
//     the scalar it replaces" rule it stays POWER9-gated. On POWER9 it wins
//     ~1.24×.
//
// The previous ISA-3.0 LXVB16X/STXVB16X (which forced a shared POWER9 gate) was
// replaced by LXVD2X/STXVD2X + a VPERM byte-reversal. Both are vars (not consts)
// so the dispatch test can also drive the scalar fallback.
var (
	hasVSXDecode = cpu.PPC64.IsPOWER8
	hasVSXEncode = cpu.PPC64.IsPOWER9
)

func encode(dst []byte, src []uint32, n int) int {
	cl := controlLen(n)
	groups := n / 4
	ctrl := dst[:cl]
	data := dst[cl:]
	safe := 0
	if hasVSXEncode {
		safe = encodeSafeGroups(ctrl, src, groups, len(data))
	}
	consumed := 0
	if safe > 0 {
		consumed = encodeGroupsVSX(&data[0], &ctrl[0], &src[0], safe,
			&encodeShuffleTablePerm[0][0], &lengthTable[0])
	}
	dp := encodeTail(dst, src, n, safe, consumed)
	return cl + dp
}
