// Code generated by go-asmgen. DO NOT EDIT.

//go:build s390x

#include "textflag.h"

TEXT ·encodeGroupsVX(SB), NOSPLIT, $0-56
	MOVD data+0(FP), R1
	MOVD ctrl+8(FP), R2
	MOVD src+16(FP), R3
	MOVD groups+24(FP), R4
	MOVD perm+32(FP), R5
	MOVD lens+40(FP), R6
	MOVD $0, R7
	ADD R2, R4, R4
	VZERO V1
loop:
	CMPBGE R2, R4, done
	MOVBZ (R2), R9
	SLD $4, R9, R8
	ADD R5, R8, R8
	VL (R8), V2
	VL (R3), V0
	VPERM V0, V1, V2, V3
	VST V3, (R1)
	ADD R6, R9, R8
	MOVBZ (R8), R9
	ADD R9, R1, R1
	ADD R9, R7, R7
	ADD $16, R3, R3
	ADD $1, R2, R2
	BR loop
done:
	MOVD R7, ret+48(FP)
	RET

