//go:build loong64

package streamvbyte

// encodeGroupsLSX compacts `groups` complete groups of four uint32 into the data
// stream using the LSX byte shuffle vshuf.b: each iteration loads one
// (precomputed) control byte, loads the 16 source bytes of the group, loads the
// encodeShuffleTablePerm[ctrl] mask, shuffles (result[i] = src[mask[i]] for
// mask[i] in 0..15, or 0 when mask[i] == 16 which selects an all-zero companion
// register, clearing the unused trailing bytes), stores 16 bytes at the running
// data cursor, and advances the data pointer by lengthTable[ctrl]. Only
// lengthTable[ctrl] bytes are significant; the trailing zeros are overwritten by
// the next group (or left in the EncodedMaxLen slack). Returns the data bytes
// written. The caller guarantees 16 writable data bytes at every requested group.
// Generated by go-asmgen (encode_loong64_gen.go), in encode_loong64.s. vshuf.b
// has no high-bit-zeroes rule, so it uses encodeShuffleTablePerm (zero -> index
// 16) and a zero register, like the VPERM targets.
func encodeGroupsLSX(data *uint8, ctrl *uint8, src *uint32, groups int, perm *uint8, lens *uint8) int

func encode(dst []byte, src []uint32, n int) int {
	cl := controlLen(n)
	groups := n / 4
	ctrl := dst[:cl]
	data := dst[cl:]
	safe := encodeSafeGroups(ctrl, src, groups, len(data))
	consumed := 0
	if safe > 0 {
		consumed = encodeGroupsLSX(&data[0], &ctrl[0], &src[0], safe,
			&encodeShuffleTablePerm[0][0], &lengthTable[0])
	}
	dp := encodeTail(dst, src, n, safe, consumed)
	return cl + dp
}
