//go:build s390x

package streamvbyte

// encodeGroupsVX compacts `groups` complete groups of four uint32 into the data
// stream using the vector-facility VPERM on z13+ (baseline, no runtime dispatch).
// Each iteration loads one (precomputed) control byte, loads the 16 source bytes
// of the group, loads the encodeShuffleTablePermBE[ctrl] mask, permutes the
// significant little-endian value bytes contiguously into the data stream (with
// zero bytes pulled from an all-zero companion register for the unused trailing
// positions), stores 16 bytes at the running data cursor, and advances the data
// pointer by lengthTable[ctrl]. Only lengthTable[ctrl] bytes are significant; the
// trailing zeros are overwritten by the next group (or left in the EncodedMaxLen
// slack). Returns the data bytes written. The caller guarantees 16 writable data
// bytes at every requested group. Generated by go-asmgen (encode_s390x_gen.go),
// in encode_s390x.s.
//
// s390x is big-endian: a source uint32 is stored MSB-first in memory while the
// emitted data stream must stay LSB-first, so encodeShuffleTablePermBE pulls each
// lane's value bytes from element L*4+(3-j) (see tables.go). This per-lane
// reversal is the inverse of the decode permTableBE and is pinned by a
// position-dependent qemu test.
func encodeGroupsVX(data *uint8, ctrl *uint8, src *uint32, groups int, perm *uint8, lens *uint8) int

func encode(dst []byte, src []uint32, n int) int {
	cl := controlLen(n)
	groups := n / 4
	ctrl := dst[:cl]
	data := dst[cl:]
	safe := encodeSafeGroups(ctrl, src, groups, len(data))
	consumed := 0
	if safe > 0 {
		consumed = encodeGroupsVX(&data[0], &ctrl[0], &src[0], safe,
			&encodeShuffleTablePermBE[0][0], &lengthTable[0])
	}
	dp := encodeTail(dst, src, n, safe, consumed)
	return cl + dp
}
