//go:build amd64

package streamvbyte

// encodeGroupsSSE compacts `groups` complete groups of four uint32 into the data
// stream using SSSE3 PSHUFB: each iteration loads one (precomputed) control byte,
// loads the 16 source bytes of the group (four uint32), applies the
// encodeShuffleTable[ctrl] compaction mask (PSHUFB writes zero for any mask byte
// with bit 7 set, which clears the unused trailing bytes), stores 16 bytes at the
// running data cursor, and advances the data pointer by lengthTable[ctrl]. Only
// lengthTable[ctrl] bytes are significant; the extra trailing zeros are
// overwritten by the next group (or left in the EncodedMaxLen slack for the last
// group). Returns the data bytes written. The caller guarantees 16 writable data
// bytes at every requested group. Generated by go-asmgen (encode_amd64_gen.go),
// in encode_amd64.s.
func encodeGroupsSSE(data *uint8, ctrl *uint8, src *uint32, groups int, shuf *uint8, lens *uint8) int

func encode(dst []byte, src []uint32, n int) int {
	cl := controlLen(n)
	groups := n / 4
	ctrl := dst[:cl]
	data := dst[cl:]
	safe := 0
	consumed := 0
	if hasSSSE3 {
		safe = encodeSafeGroups(ctrl, src, groups, len(data))
		if safe > 0 {
			consumed = encodeGroupsSSE(&data[0], &ctrl[0], &src[0], safe,
				&encodeShuffleTable[0][0], &lengthTable[0])
		}
	}
	dp := encodeTail(dst, src, n, safe, consumed)
	return cl + dp
}
