// Package streamvbyte implements Stream VByte — the SIMD-friendly byte-oriented
// integer compression codec of Lemire, Kurz & Rupp (Information Processing
// Letters 130, 2018; arXiv:1709.08990). A []uint32 is encoded as a *control
// stream* of 2-bit lengths (one byte per four integers, four 2-bit codes each,
// least-significant code first) followed by a *data stream* of each integer's
// significant little-endian bytes (1..4, code+1).
//
// The wire format is byte-for-byte identical to the reference C library
// (github.com/lemire/streamvbyte, standard 1234 variant), so encoded output
// interoperates in both directions.
//
// Decode is the SIMD star: each control byte indexes a 256-entry shuffle LUT
// that, in a single PSHUFB/VTBL/VPERM/vrgather/VSHUF, spreads four packed
// integers' bytes into four zero-extended uint32 lanes. The hot decode loop is
// assembly (generated by go-asmgen) on all six of Go's 64-bit SIMD targets —
// amd64, arm64, ppc64le, s390x, riscv64, loong64 — with a portable scalar
// fallback elsewhere. No cgo, no GOEXPERIMENT, plain `go build`.
package streamvbyte

import "encoding/binary"

// EncodedMaxLen returns an upper bound on the number of bytes Encode needs for n
// integers: the control stream ((n+3)/4 bytes) plus the worst case of 4 data
// bytes per integer. dst passed to Encode must be at least this long.
func EncodedMaxLen(n int) int {
	if n <= 0 {
		return 0
	}
	return (n+3)/4 + 4*n
}

// controlLen returns the number of control bytes for n integers.
func controlLen(n int) int { return (n + 3) / 4 }

// Encode writes the Stream VByte encoding of src into dst and returns the number
// of bytes written. dst must have length >= EncodedMaxLen(len(src)); Encode
// panics otherwise. The layout is [control bytes][data bytes], matching the
// canonical reference format.
func Encode(dst []byte, src []uint32) int {
	n := len(src)
	if n == 0 {
		return 0
	}
	cl := controlLen(n)
	if len(dst) < cl {
		panic("streamvbyte: dst too short")
	}
	// Zero the control region; codes are OR-ed in.
	ctrl := dst[:cl]
	for i := range ctrl {
		ctrl[i] = 0
	}
	data := dst[cl:]
	dp := 0
	var key byte
	shift := uint(0)
	ki := 0
	for c := 0; c < n; c++ {
		if shift == 8 {
			ctrl[ki] = key
			ki++
			key = 0
			shift = 0
		}
		val := src[c]
		var code byte
		switch {
		case val < 1<<8:
			data[dp] = byte(val)
			dp++
			code = 0
		case val < 1<<16:
			binary.LittleEndian.PutUint16(data[dp:], uint16(val))
			dp += 2
			code = 1
		case val < 1<<24:
			data[dp] = byte(val)
			data[dp+1] = byte(val >> 8)
			data[dp+2] = byte(val >> 16)
			dp += 3
			code = 2
		default:
			binary.LittleEndian.PutUint32(data[dp:], val)
			dp += 4
			code = 3
		}
		key |= code << shift
		shift += 2
	}
	ctrl[ki] = key // last (partial) key
	return cl + dp
}

// Decode reads n integers in Stream VByte format from src (control bytes
// followed by data bytes, as produced by Encode) into dst and returns the number
// of bytes consumed from src. dst must have length >= n; Decode panics
// otherwise. Decode(dst, Encode(dst2, src), len(src)) reproduces src exactly.
func Decode(dst []uint32, src []byte, n int) int {
	if n == 0 {
		return 0
	}
	if len(dst) < n {
		panic("streamvbyte: dst too short")
	}
	cl := controlLen(n)
	read := decode(dst[:n], src, n)
	return cl + read
}
