// Package streamvbyte implements Stream VByte — the SIMD-friendly byte-oriented
// integer compression codec of Lemire, Kurz & Rupp (Information Processing
// Letters 130, 2018; arXiv:1709.08990). A []uint32 is encoded as a *control
// stream* of 2-bit lengths (one byte per four integers, four 2-bit codes each,
// least-significant code first) followed by a *data stream* of each integer's
// significant little-endian bytes (1..4, code+1).
//
// The wire format is byte-for-byte identical to the reference C library
// (github.com/lemire/streamvbyte, standard 1234 variant), so encoded output
// interoperates in both directions.
//
// Both directions are SIMD: each control byte indexes a 256-entry shuffle LUT
// that, in a single PSHUFB/VTBL/VPERM/vrgather/VSHUF, either spreads four packed
// integers' bytes into four zero-extended uint32 lanes (decode) or, with the
// mirror-image LUT, compacts four uint32 lanes' significant bytes back into the
// data stream (encode). The hot loops are assembly (generated by go-asmgen) on all
// six of Go's 64-bit SIMD targets — amd64, arm64, ppc64le, s390x, riscv64,
// loong64 — with a portable scalar fallback elsewhere. Per-group length
// classification stays scalar, so decode (a fully vectorised loop) gains more than
// encode. No cgo, no GOEXPERIMENT, plain `go build`.
package streamvbyte

// EncodedMaxLen returns an upper bound on the number of bytes Encode needs for n
// integers: the control stream ((n+3)/4 bytes) plus the worst case of 4 data
// bytes per integer. dst passed to Encode must be at least this long.
func EncodedMaxLen(n int) int {
	if n <= 0 {
		return 0
	}
	return (n+3)/4 + 4*n
}

// controlLen returns the number of control bytes for n integers.
func controlLen(n int) int { return (n + 3) / 4 }

// Encode writes the Stream VByte encoding of src into dst and returns the number
// of bytes written. dst must have length >= EncodedMaxLen(len(src)); Encode
// panics otherwise. The layout is [control bytes][data bytes], matching the
// canonical reference format.
//
// On the six 64-bit SIMD targets the data-compaction step runs in assembly (one
// shuffle per group of four integers, the inverse of the decode shuffle); the
// portable build and the < 4 tail use the shared scalar encoder. The wire bytes
// are identical on every path.
func Encode(dst []byte, src []uint32) int {
	n := len(src)
	if n == 0 {
		return 0
	}
	if len(dst) < EncodedMaxLen(n) {
		panic("streamvbyte: dst too short")
	}
	return encode(dst, src, n)
}

// controlByte returns the Stream VByte control byte (four 2-bit length codes,
// least-significant code first) for a group of four uint32 starting at src[i].
// The same length classification (code = byte-length-1) drives both the scalar
// and SIMD encoders, keeping the wire format in one place.
func controlByte(a, b, c, d uint32) byte {
	return code(a) | code(b)<<2 | code(c)<<4 | code(d)<<6
}

func code(v uint32) byte {
	switch {
	case v < 1<<8:
		return 0
	case v < 1<<16:
		return 1
	case v < 1<<24:
		return 2
	default:
		return 3
	}
}

// Decode reads n integers in Stream VByte format from src (control bytes
// followed by data bytes, as produced by Encode) into dst and returns the number
// of bytes consumed from src. dst must have length >= n; Decode panics
// otherwise. Decode(dst, Encode(dst2, src), len(src)) reproduces src exactly.
func Decode(dst []uint32, src []byte, n int) int {
	if n == 0 {
		return 0
	}
	if len(dst) < n {
		panic("streamvbyte: dst too short")
	}
	cl := controlLen(n)
	read := decode(dst[:n], src, n)
	return cl + read
}
